# Ejercicio 6
## Detección de Amarillos en tiempo real

### Librerias

In [1]:
import numpy as np
import cv2 as cv

### Limites de Colores

In [ ]:
def get_limits(color, delta):
    """
    Obtener los límites de un color en el espacio HSV

    Args:
        color (list): color en BGR
        delta (int): margen de error

    Returns:
        np.array: color en HSV
        np.array: límite inferior
        np.array: límite superior
    """
    # Convertir el color a HSV
    rgb_color = np.uint8([[color]])
    hsv_color = cv.cvtColor(rgb_color, cv.COLOR_BGR2HSV)

    # Definir los limites del color en HSV
    h_value = int(hsv_color[0][0][0])
    min_limit = np.array([max(h_value - delta, 0), 100, 100], dtype=np.uint8)
    max_limit = np.array([min(h_value + delta, 179), 255, 255], dtype=np.uint8)

    return hsv_color[0][0], min_limit, max_limit

In [3]:
# Definir colores en BGR
RED = [0, 0, 255]
GREEN = [0, 255, 0]
BLUE = [255, 0, 0]
YELLOW = [0, 255, 255]

# Obtener límites para cada color
red, red_min, red_max = get_limits(color=RED, delta=15)
green, green_min, green_max = get_limits(color=GREEN, delta=15)
blue, blue_min, blue_max = get_limits(color=BLUE, delta=15)
yellow, yellow_min, yellow_max = get_limits(color=YELLOW, delta=15)

# Mostrar resultados
red, red_min, red_max, green, green_min, green_max, blue, blue_min, blue_max, yellow, yellow_min, yellow_max


(array([  0, 255, 255], dtype=uint8),
 array([  0, 100, 100], dtype=uint8),
 array([ 15, 255, 255], dtype=uint8),
 array([ 60, 255, 255], dtype=uint8),
 array([ 45, 100, 100], dtype=uint8),
 array([ 75, 255, 255], dtype=uint8),
 array([120, 255, 255], dtype=uint8),
 array([105, 100, 100], dtype=uint8),
 array([135, 255, 255], dtype=uint8),
 array([ 30, 255, 255], dtype=uint8),
 array([ 15, 100, 100], dtype=uint8),
 array([ 45, 255, 255], dtype=uint8))

### Captura de video